name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/AlteredTrader-1.0.0.AppImage
            build/AlteredTrader\ Setup\ 1.0.0.exe
            build/AlteredTrader_mac_x64.zip
            build/AlteredTrader_mac_arm64.zip